spring:
  application:
    name: management
  app:
    jwt-secret: ${JWT_SECRET}
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB

  datasource:
    url: jdbc:postgresql://localhost:5432/managementservice
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-2
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

app:
  awsServices:
    bucketName: gtp-group-three-lms
management:
  endpoints:
    web:
      exposure:
        exclude: 'health,metrics,info'
  httpexchanges:
    recording:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: https://${eureka-server.hostname}:${eureka-server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true

