spring:
  application:
    name: management
  app:
    jwt-secret: ${JWT_SECRET}

  datasource:
    url: jdbc:postgresql://99.81.103.204:5432/managementservice
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-2
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

app:
  awsServices:
    bucketName: gtp-group-three-lms

server:
  port: ${SERVER_PORT}

eureka-server:
  port: ${EUREKA_PORT}
  hostname: ${EUREKA_HOSTNAME}

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-server.hostname}:${eureka-server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true

