spring:
  app:
    jwtSecret: ${JWT_SECRET}
  application:
    name: service-provider-profile
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


aws:
  accessKeyId: ${S3_ACCESS_KEY_ID}
  secretAccessKey: ${S3_SECRET_ACCESS_KEY}
  s3:
    bucketName: ${BUCKET_NAME}
    region: us-east-2

