services:
  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    container_name: auth-service-container
    restart: on-failure:3
    ports:
      - "9090:9090"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./authservice/.env
    volumes:
      - prox-volume

  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: eureka-server-container
    restart: on-failure:3
    ports:
      - "9091:9091"
    networks:
      - proximity-finder-network
      - training-shared-network
    volumes:
      - prox-volume

  management:
    build:
      context: ./management
      dockerfile: Dockerfile
    container_name: management-service-container
    restart: on-failure:3
    ports:
      - "9092:9092"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./management/.env
    volumes:
      - prox-volume


  provider-profile-service:
    build:
      context: ./provider-profile-service
      dockerfile: Dockerfile
    container_name: provider-profile-service-container
    restart: on-failure:3
    ports:
      - "9093:9093"
    networks:
      - proximity-finder-network
      - training-shared-network
    env_file:
      - ./provider-profile-service/.env
    volumes:
      - prox-volume

networks:
  proximity-finder-network:
    driver: bridge
  training-shared-network:
    driver: bridge

volumes:
  prox-volume: