spring:
  application:
    name: "gateway-server"
  app:
    jwtSecret: ${JWT_SECRET}
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: payment-method-route
          uri: lb://service-provider-profile
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationPreFilter

        - id: management-service
          uri: lb://management
          predicates:
            - Path=/api/v1/**
          filters:
            - name: AuthenticationPreFilter
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    gateway:
      enabled: true

eureka-server:
  port: ${EUREKA_PORT:8761}
  hostname: ${EUREKA_HOSTNAME:localhost}

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-server.hostname}:${eureka-server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
        http:
          server:
            reactive: DEBUG
        web:
          reactive: DEBUG

