spring:
  application:
    name: "gatewayserver"
  app:
    jwtSecret: ${JWT_SECRET}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globals:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:4200"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationPreFilter

server:
  port: 8071

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
        http:
          server:
            reactive: DEBUG
        web:
          reactive: DEBUG