spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service_db
    username: postgres
    password: deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 9090


