spring:
  application:
    name: request-management-service
  app:
    jwtSecret: SGEIE84358FDBOUDD723HE084HTDF713EGSJDIG5HS72GSD91BSAIFSY3EESDT5TGVKLNA9363BA3E


  datasource:
    url: jdbc:postgresql://localhost:5432/quote_db
    username: postgres
    password: deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 9000

aws:
  accessKeyId: AKIAYS2NQEZAT47GJVPQ
  secretAccessKey: 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
  s3:
    bucketName: gtp-group-three-lms
    region: us-east-2


