spring:
  application:
    name: "authservice"
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  app:
    jwtSecret: "SGEIE84358FDBOUDD723HE084HTDF713EGSJDIG5HS72GSD91BSAIFSY3EESDT5TGVKLNA9363BA3E"
  datasource:
    url: jdbc:postgresql://localhost/user-service_db
    username: postgres
    password: deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
aws:
  accessKeyId: AKIAYS2NQEZAT47GJVPQ
  secretAccessKey: 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
  s3:
    bucketName: gtp-group-three-lms
    region: us-east-2

email:
  from-address: Proximity Team <samuel.amo@amalitechtraining.org>
  subject: Reset Your Password
  reset-url: http://localhost:4200/reset-password?token=
