spring:
  application:
    name: "authservice"
  app:
    jwtSecret: "SGEIE84358FDBOUDD723HE084HTDF713EGSJDIG5HS72GSD91BSAIFSY3EESDT5TGVKLNA9363BA3E"
  datasource:
    url: jdbc:postgresql://localhost/user-service_db
    username: postgres
    password: AhZu@#2024
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
aws:
  accessKeyId: AKIAYS2NQEZAT47GJVPQ
  secretAccessKey: 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
  s3:
    bucketName: gtp-group-three-lms
    region: us-east-2

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka/

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
#        web: TRACE

frontend:
  url: "http://localhost:4200"
