spring:
  application:
  name: "authservice"
  app:
    jwtSecret: ${JWT_SECRET}
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: ${SERVER_PORT}
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
frontend:
  url: ${FRONTEND_URL}
