spring:
  application:
    name: management

  datasource:
    url: jdbc:postgresql://localhost:5432/managementservice
    username: postgres
    password: AhZu@#2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloud:
  aws:
    region:
      static: us-east-2
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

app:
  awsServices:
    bucketName: gtp-group-three-lms

CLOUD_AWS_CREDENTIALS_ACCESS_KEY: AKIAYS2NQEZAT47GJVPQ
CLOUD_AWS_CREDENTIALS_SECRET_KEY: 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
