spring:
  application:
    name: help-and-support
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

  app:
    jwtSecret: ${JWT_SECRET}

  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/support_db}
    username: ${POSTGRES_USER:postgres}
    password: ${PASSWORD:deeplearning89629202@#$!}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: ${PORT:8040}

email:
  to-address: ${TO_ADDRESS:SWIFT CRAFT Support<samuel.amo@amalitechtraining.org>}

