spring:
  application:
    name: service-provider-profile
  datasource:
    url: jdbc:postgresql://localhost:5432/provider-service_db
    username: postgres
    password: deeplearning89629202@#$!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


aws:
  accessKeyId: AKIAYS2NQEZAT47GJVPQ
  secretAccessKey: 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
  s3:
    bucketName: gtp-group-three-lms
    region: us-east-2

